version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ghello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-adegznlgzh5c"
s3_prefix = "fhello"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

