AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  minik

  Sample SAM Template for minik

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  CertArn:
    Type: String

  HZId:
    Type: String

Resources:
  HelloWorldFunction:
    Name: HelloWorld
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: lambda_handler.app
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: GET
        WhyWorld:
          Type: Api
          Properties:
            Path: /why/{reason}
            Method: GET

# Adding Domain Name
# This includes the TLS certificate I made with ACM
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn:
        Ref: CertArn
      DomainName: eab.ceeej.com
      SecurityPolicy: TLS_1_2
      EndpointConfiguration:
        Types:
          - REGIONAL


  # Finally setting up the URL mapping for the API gateway
  UrlMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName:
        Ref: DomainName
      RestApiId:
        Ref: ServerlessRestApi
      Stage: 
        Ref: ServerlessRestApiProdStage
    DependsOn:
      - HelloWorldFunction
      - ServerlessRestApi

# Next is creating the A record
  LambdaDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Ref: HZId
      Name: eab.ceeej.com.
      Type: A
      AliasTarget:
        HostedZoneId: 
          Fn::GetAtt:
            - DomainName
            - RegionalHostedZoneId
        DNSName: 
          Fn::GetAtt: 
            - DomainName
            - RegionalDomainName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  RegionalDomainName:
    Value: !GetAtt 
      - DomainName
      - RegionalDomainName
  RegionalHostedZoneId:
    Value: !GetAtt 
      - DomainName
      - RegionalHostedZoneId